### ISSUE TITLE
With Ramps Steppers Not Working !

### ISSUE THREAD

**Issue by gumush** [euphy/polargraphcontroller#10]
Demo of Accelstepper libraries is working with multiple step motors. 
# ifndef MOTHERBOARD

//#define MOTHERBOARD POLARSHIELD
# define MOTHERBOARD RAMPS14

//#define MOTHERBOARD TFTSHIELD
# endif

//#define USE_LC

Check pins of motors with 
# define DEBUG

With this firmware motors just have a small buzzing.

**Comment by euphy** [comment]
Insufficient information, what firmware (version, source)? What commands are you sending, what are you expecting, are you receiving any messages back from the machine etc. What have you done so far. What setup guide are you following, what have you already tried.
Please think about what information I would be likely to need to be able to help diagnose a problem. And give it.

**Comment by euphy** [comment]
I'm closing this issue as not defined.
