### ISSUE TITLE
Ubuntu error on port

### ISSUE THREAD

**Issue by mskogly** [euphy/polargraphcontroller#11]
Running the .sh from https://github.com/euphy/polargraphcontroller/releases/tag/2016-03-29-10-23. When I change port settings  to  controller.machine.serialport=/dev/ttyUSB0 (it is correct and works when testing from arduino ide) in default.properties.txt i get the following error when starting the shellscript:

mskogly@stav4:~/Downloads/PG$ sudo ./polargraphcontroller
Running polargraph controller
Successfully loaded properties file /home/mskogly/Downloads/PG/default.properties.txt
machine size: 29059.0, 19926
windowHeight:362
Polygonizer: 0
PolygonizerLength: 0.0
Finished loading configuration from properties file.
ControlP5 2.2.5 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
Java HotSpot(TM) Server VM warning: You have loaded library /home/mskogly/Downloads/PG/lib/libjSSC-2.8.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Serial ports available on your machine:
/dev/ttyS0 /dev/ttyS1 /dev/ttyS2 /dev/ttyS3 /dev/ttyS4 /dev/ttyS5 /dev/ttyS6 /dev/ttyS7 /dev/ttyS8 /dev/ttyS9 /dev/ttyS10 /dev/ttyS11 /dev/ttyS12 /dev/ttyS13 /dev/ttyS14 /dev/ttyS15 /dev/ttyS16 /dev/ttyS17 /dev/ttyS18 /dev/ttyS19 /dev/ttyS20 /dev/ttyS21 /dev/ttyS22 /dev/ttyS23 /dev/ttyS24 /dev/ttyS25 /dev/ttyS26 /dev/ttyS27 /dev/ttyS28 /dev/ttyS29 /dev/ttyS30 /dev/ttyS31 /dev/ttyUSB0
About to connect to serial port in slot 0
Get serial port no: 0
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: jssc.SerialNativeInterface.openPort(Ljava/lang/String;Z)J
    at jssc.SerialNativeInterface.openPort(Native Method)
    at jssc.SerialPort.openPort(SerialPort.java:158)
    at processing.serial.Serial.<init>(Unknown Source)
    at processing.serial.Serial.<init>(Unknown Source)
    at polargraphcontroller.setup(polargraphcontroller.java:620)
    at processing.core.PApplet.handleDraw(PApplet.java:2361)
    at processing.core.PGraphicsJava2D.requestDraw(PGraphicsJava2D.java:240)
    at processing.core.PApplet.run(PApplet.java:2256)
    at java.lang.Thread.run(Thread.java:745)

**Comment by mskogly** [comment]
Another bug, mentioned before. When clicking setup / ports (only possible if controller window hasn't been maximized), the port options that are not withing the initial window size isnt clickable.

**Comment by mskogly** [comment]
Solved the last one  by simply counting the number of ports listed. Usb0 was the last one, #32.

**Comment by euphy** [comment]
The second issue duplicates #7 - please add your comment to that issue and remove them from here, thanks!

**Comment by euphy** [comment]
@mskogly this is two separate issues - are these still issues for you? If so, can you separate them please? If not, please close the issue.
