### ISSUE TITLE
Communication error ?

### ISSUE THREAD

**Issue by martblek** [euphy/polargraphcontroller#12]
Hi ,
I just build simple polargraph based on your firmware for polarshield.
My HW is arduino mega with ramps1.4. Correctly edited source for ramps and compiled without problem.
Started PolargraphController set serial port and messages appears. seems to OK.

FW and Controller from 2016-03-29

`Successfully connected to port /dev/ttyACM0

incoming: ���POLARGRAPH ON!
incoming: v1.3.1
incoming: Hardware: RAMPS14
incoming: Servo 4
incoming: Loaded machine width:650
incoming: Loaded machine height:255
incoming: Loaded mm per rev:95.00
incoming: Loaded motor steps per rev:67
incoming: Loaded motor step multiplier:18432
incoming: Loaded machine name:PG01
incoming: Loaded down pos:90
incoming: Loaded up pos:180
incoming: penWidth: 0.00
incoming: Recalc mmPerStep (0.00), stepsPerMM (12999.41)
incoming: Recalc pageWidth in steps (8449617)
incoming: Recalc pageHeight in steps (3314849)
incoming: Card failed, or not present
incoming: Released motors
incoming: READY_200
incoming: READY_200
`

but if i click to queue this appears in console:
`queue clicked.

Dispatching command: C02,1.02,END
Last command:C02,1.02,END
incoming: MSG,E,_������������������������������������������������������������������������������������
/ etc, etc , lots of these chars.

ending with this

Bad format for hardware version - defaulting to ATMEGA328 (Uno)

and finaly after these strange chars
"not recognized"
`

**Comment by euphy** [comment]
That's a bit odd isn't it. 'not recognized' is not a string that's in the polargraph codebase, so not sure where that can be coming from ... the serial port library perhaps? Which OS are you using?

You don't actually mention what the problem is that you're having - what do you expect to see happen, and what actually happens?

**Comment by martblek** [comment]
My system is Archlinux 64bit.
Still can't get MEGA version to run. Recompiled and now i'm stuck on BUSY. I can't upload anything.
In console is all ok. but no response from arduino. Still repeating READY_200.
Anyway version for UNO running flawlessly. No problem in communication via serial port.
Same data cable is used.
Both FW versions compiled in ArduinoIDE 1.6.12

**Comment by martblek** [comment]
Seems i found ugly solution.
If i define DEBUG_COMMS in comms.ino this FW works.
But my CPU ( old P4) is overloaded coz this many printed informations :)
