### ISSUE TITLE
processing 3 updates / errors

### ISSUE THREAD

**Issue by megrimm** [euphy/polargraphcontroller#13]
any plans for processing 3 updates?

some errors im getting:

- awt support has been removed in processing 3 so the addMouse stuff is broken.
- The function "add()" expects parameters like: "add(Component)"

thats as far as i got but thought i would ask if updates planned.

thanks!

**Comment by euphy** [comment]
Ah ... no plans for Processing 3. There's lots of breaking changes, the main deal-breakers seem to be the multi-window stuff which I've never seen done in P3. Maybe it's possible!
