### ISSUE TITLE
When window is scaled buttons are not usable

### ISSUE THREAD

**Issue by MurKit** [euphy/polargraphcontroller#14]
Ubuntu 14.04 32bit polargraphcontroller 2.4.0

I have downloaded compiled version and compiled one myself.
The result is the same. For some reason I have 31 ttyS* serial ports.
So program adds ttyUSB to the end of that list
...
Adding /dev/ttyS31
Adding /dev/ttyUSB0
In order to get my ttyUSB port, I have to resize the Serial Port window, but inside it only first ten buttons are clickable, so I cannot choose my port anyway.

Here is a screenshot http://pasteboard.co/56E11nDbK.png

And the main window behaves the same exact way. If resized of full screened, most of buttons become unusable.

**Comment by MurKit** [comment]
Update: 
Edited default.properties.txt, set my USB port as default.
Still no connection.

About to connect to serial port in slot 32
Get serial port no: 32
Successfully connected to port /dev/ttyUSB0
Error, disabling serialEvent() for /dev/ttyUSB0
null

**Comment by MurKit** [comment]
Found temporary solution that let me connect to the Arduino + RAMPS:
Before running Polargraphcontroller from source, edit file SerialPortWindow.pde

  for (int i = 28; i < ports.length; i++) {
    println("Adding " + ports[i]);
    r.addItem(ports[i], i);
  }

This 28 instead of 0 just skips first 28 serial ports of my Linux, so I can choose ttyUSB0.

**Comment by euphy** [comment]
Good solution - but I wonder why the direct modifications to default.properties.txt didn't work?

I think radio buttons isn't the right pattern for this, a drop down is a better choice.

**Comment by MurKit** [comment]
Would it be a sane task to remake controller in Python? Is it possible in some real time limits?

**Comment by euphy** [comment]
Definitely possible to make this in any other language, and I love Python. But it's not a trivial task, so I don't have time to do it myself.
