### ISSUE TITLE
Request for reversed order in serial dropdown

### ISSUE THREAD

**Issue by MurKit** [euphy/polargraphcontroller#16]
Could you make the order of ports in serial dropdown reversed?

Like that:
No serial conneciton
/dev/ttyUSB0
/dev/ttyS31
/dev/ttyS29
...

Just to be able not to scroll so much, USB would appear near the top.

I tried, but didn't manage to do it myself. As it is not possible to make size of dropdown bigger than 150, because lower items are not selectable then.

**Comment by euphy** [comment]
How would I be sure this doesn't inconvenience someone else who expects to have their ports at the beginning? Remember they have different names, on windows they are COM1 etc.

**Comment by euphy** [comment]
Closing this as no response, though I have changed how the serial ports are displayed recently, so perhaps this is less of a problem now anyway.
