### ISSUE TITLE
How to run the controller on Rpi?

### ISSUE THREAD

**Issue by tomtobback** [euphy/polargraphcontroller#18]
I've been running the compiled version of the controller on my Linux Ubuntu machine but now i'd like to set it up on a Raspberry Pi. I don't see any compiled files, so I tried running it from the Processing source code. But Processing is only available in version 3 for the Rpi, and i see the controller is written for Processing 2.2.1
Any workaround?
Thanks

**Comment by tomtobback** [comment]
OK i spoke too soon, it seems the compiled linux32 version runs on my Rpi. I'm trying to get the Serial working now, feel free to close the issue if this should work!

**Comment by markcra** [comment]
I think it needs to be compiled on a Raspberry Pi for the serial to work. I jumped through a few hoops to get Processing 2.2.1 to run on a Raspberry Pi, eventually following the tutorial below:
http://scruss.com/blog/2014/01/07/processing-2-1-oracle-java-raspberry-pi-serial-arduino-%E2%98%BA/

**Comment by tomtobback** [comment]
thanks a lot Mark, i got Processing2.2.1 running on my Rpi with those instructions, and even the Serial connection with the Arduino worked, although the Serial pop-up window was still blank on the first try: i need to open/close/open it to see the list. But unfortunately the 'Render pixels..' pop-up does not work; it is blank and open/close/open does not do the trick. Other commands 'move pen to point' do work, so i got very close, but i'm no expert in Processing nor Java to debug this further. Thanks for the help, just wondering, did you get it the polargraphcontroller working on Rpi?
I tried also with the pre-compiled versions for linux32/64 but same problem with the 'Render pixels..' pop-up.

**Comment by markcra** [comment]
Yes, had it working on a Raspberry Pi recently, although it was with an ancient fork of euphy's code which I had been playing with (adding rotary pots and spirographs, see https://www.instagram.com/p/BTt_z2Olkjk/). I've since updated to the latest version of polargraphcontroller but haven't fully tested it. I've never played with render pixels.

**Comment by tomtobback** [comment]
thanks Mark. the only place i got stuck at with the Raspberry Pi was the popup-box for 'Render pixels..' which came up empty (10 May 2017 release). i did not try any vector drawing but i suppose that would work because it does not launch an additional popup and the 'move pen to point' was working properly. anyway, i'm running my basic polargraph (not very precise!) from an old pentium4 laptop with Lubuntu now, works great http://cassiopeia.hk/polargraph/
