### ISSUE TITLE
Concurrentmodificationexception in debugging console after crash

### ISSUE THREAD

**Issue by OneTrueTai** [euphy/polargraphcontroller#19]
After going to Generate Commands, the whole program becomes unresponsive. After the crash it highlights line 1624, 

" if (forceRebuild || (commandQueue.hashCode() != lastCommandQueueHash)) "

As well as reading "Concurrentmodificationexception" in the console. I have downloaded the recommended Processing version as well as other software. If I'm not mistaken, this was a problem fixed earlier in line 2049?
 
"   }
  catch (ConcurrentModificationException cme)
  {
    // not doing anything with this exception - I don't mind if it's wrong on the screen for a second or two.
    println("Caught the pesky ConcurrentModificationException: " + cme.getMessage());
  } "

**Comment by euphy** [comment]
Generate commands from where? Can you help me replicate the issue?

**Comment by OneTrueTai** [comment]
Step by step. I load the program from Processing, because the Java exe file didnt want to run. https://gyazo.com/a0b5918ab966d6b975e6709984751a34 (Console on startup if this helps any)
Start the Queue
Set Home
Load Image File
Load ![fire](https://user-images.githubusercontent.com/43833932/46511262-8f617080-c81b-11e8-8a81-3770d2e4be11.png)
Select Area, Show Density Range off
Mask the white area. 
Render Pixels (Top Left, Var Freq Square Wave, Lift Pen over Masked.)
Generate Commands
Crash 
The queue that would be sent goes from row: 24948.0 to 35262.0, skipping 18 numbers each time, the queue ending with Dir:SW and CME in orange at the top bar of the queue.
The Properties file if it'll help: 
[default.properties.txt](https://github.com/euphy/polargraphcontroller/files/2448661/default.properties.txt)

If there is anything else you may need, please ask for it!

**Comment by OneTrueTai** [comment]
Have you gotten any idea or progress? It’s been a month.

**Comment by euphy** [comment]
Hello, this is a fun one! I have two bad ways to solve it.
1) Turn "show queue preview" off (the small toggle buttons) at the end of the buttons on the input tab.
2) Wrap the call to queuePreview in a try/catch:

(line 843 onwards:
```
  ...
  showGroupBox();
  showCurrentMachinePosition();

  try {
    if (displayingQueuePreview)
      previewQueue();
  }
  catch (ConcurrentModificationException cme)
  {
    // not doing anything with this exception - I don't mind if it's wrong on the screen for a second or two.
    println("Caught CME coming from previewQueue(): " + cme.getMessage());
  }

  if (displayingInfoTextOnInputPage)
    showText(250,45);
  drawStatusText((int)statusTextPosition.x, (int)statusTextPosition.y);
  ...
```

I'm not sure what the problem actually is. I did replicate the issue and got the exception you described. There's nothing on that line (1624) that should be able to throw a concurrent modification exception!

I haven't dug into it. It looks to me that the list of pixels being extracted takes so long to be processed that some other process has time to interfere.

It's a very long list, and is quite unusual.

**Comment by euphy** [comment]
I've pushed a try/catch, not the best way to do it, but it seems to work! See if it works for you.
