### ISSUE TITLE
Window resizing on Mac OS 10.10

### ISSUE THREAD

**Issue by abcdev** [euphy/polargraphcontroller#5]
If the window is resized everything that moved into the area that revealed because of the resizing becomes inaccessible. only fix is to be to start with the desired window size.

- Making the window smaller has no negative effects

**Comment by euphy** [comment]
I noticed this too on Windows 10. It's to do with the way the buttons "re-flow" when the window is resized in Processing 2. The workaround is to resize, then "save config", and reopen the controller with the new window size. I'll have a look at this.

**Comment by euphy** [comment]
I think this is fixed - thanks to https://github.com/sojamo/controlp5/issues/26 which has a solution that I've implemented.
